version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
     - "80:80"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125/udp"
     - "8126:8126"
  devenv:
    build: devenv/.
    ports:
    - "2181:2181"
    - "9093:9093"
    - "9094:9094"
    healthcheck:
      test: ["CMD", "./prepare-zk.sh", "devenv", "5"]
      interval: 5s
      timeout: 10s
      retries: 10
  manager:
    build: .
    ports:
    - "8100:8100"
    command: "manager \
       -config example/example-cluster.properties \
       -srcClusters cluster1,cluster2 \
       -destClusters cluster1,cluster2 \
       -deployment ureplicator-example \
       -env deployment \
       -enableRebalance true \
       -zookeeper 10.132.0.210:2181 \
       -managerPort 8100 \
       -controllerPort 9000 \
       -initMaxNumWorkersPerRoute 5 \
       -maxNumWorkersPerRoute 10 \
       -graphiteHost graphite \
       -graphitePort 2003"
    depends_on:
    - devenv
    deploy:
      restart_policy:
        condition: on-failure
    links:
    - devenv
    healthcheck:
      test: ["CMD", "./wait-for-it.sh", "manager:8100", "60"]
      interval: 5s
      timeout: 10s
      retries: 5
  controller:
    image: ureplicator_manager
    ports:
    - "9000:9000"
    command: "controller \
          -config example/example-cluster.properties \
          -enableFederated true \
          -deploymentName ureplicator-example \
          -srcClusters cluster1,cluster2 \
          -destClusters cluster1,cluster2 \
          -helixClusterName manager-controller-ureplicator-example \
          -mode customized \
          -zookeeper 10.132.0.210:2181 \
          -port 9000 \
          -instanceId 1 \
          -hostname controller \
          -maxWorkingInstances 0 \
          -offsetRefreshIntervalInSec 0 \
          -enableAutoWhitelist false \
          -graphiteHost graphite \
          -graphitePort 2003"
    depends_on:
    - devenv
    links:
    - devenv
    healthcheck:
      test: ["CMD", "./wait-for-it.sh", "controller:9000", "60"]
      interval: 30s
      timeout: 10s
      retries: 5
  worker_1:
    image: ureplicator_manager
    command:  "worker \
        --consumer.config example/example-consumer.properties \
        --producer.config example/example-producer.properties \
        --helix.config example/example-helix-3.properties \
        --topic.mappings example/example-topicmapping.properties \
        --cluster.config example/example-cluster.properties"
    depends_on:
    - controller
    links:
    - controller
