version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
     - "80:80"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125/udp"
     - "8126:8126"
    volumes:
        - /home/shashank/graphite:/home/shashank/graphite/storage/whisper/
  devenv:
    build: devenv/.
    ports:
    - "2181:2181"
    - "9093:9093"
    - "9094:9094"
  controller:
    build: .
    ports:
    - "9000:9000"
    command: "controller \
      -mode auto \
      backUpToGit false \
      -enableAutoTopicExpansion true \
      -port 9000 \
      -refreshTimeInSeconds 10 \
      -srcKafkaZkPath 10.132.0.198:2181 \
      -zookeeper 10.132.0.198:2181 \
      -destKafkaZkPath 10.132.0.198:2181 \
      -helixClusterName replicatorpoc2 \
      -graphiteHost graphite \
      -graphitePort 2003"
    depends_on:
    - devenv
    links:
    - devenv
    healthcheck:
      test: ["CMD", "./wait-for-it.sh", "controller:9000", "60"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
        - /home/shashank/testMirrorMaker:/var/log/kafka-mirror-maker-controller
  worker:
    image: app_controller
    command:  "worker \
        --consumer.config example/example-consumer.properties \
        --producer.config example/example-producer.properties \
        --topic.mappings example/example-topicmapping.properties \
        --helix.config example/example-helix-2.properties "
    depends_on:
    - controller
    links:
    - controller
    volumes:
        - /home/shashank/testMirrorMaker:/var/log/kafka-mirror-maker-controller/
